tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'nodenv/nodenv'
tap 'thoughtbot/formulae'

# Build tools and libs
brew 'coreutils'
brew 'gmp'
brew 'libyaml'
brew 'makedepend'
brew 'pkg-config'

brew 'ack'
brew 'antigen'
brew 'awscli'
brew 'diff-so-fancy'
brew 'fasd'
brew 'gnu-tar'
brew 'goenv'
brew 'heroku'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'mas'
brew 'node-build'
brew 'nodenv-aliases'
brew 'nodenv-vars'
brew 'nodenv'
brew 'openssl'
brew 'parity'
brew 'rbenv-aliases'
brew 'rbenv-vars'
brew 'rbenv'
brew 'rcm'
brew 'ruby-build'
brew 'thefuck'
brew 'watch'
brew 'wifi-password'
brew 'yarn'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'zsh'

cask '1password'
cask 'alfred'
cask 'captain'
cask 'daisydisk'
cask 'dash'
cask 'docker'
cask 'google-chrome'
cask 'google-drive'
cask 'hyper'
cask 'iterm2'
cask 'kap'
cask 'keepingyouawake'
cask 'screenhero'
cask 'sequel-pro'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'telegram'
cask 'toggldesktop'
cask 'visual-studio-code'

mas "Noizio", id: 928871589
mas "Simplenote", id: 692867256
mas "Textual", id: 896450579
mas "Todoist", id: 585829637
