#!/bin/bash

# Sleepwatcher Sleep Script

## Disconnect headphones 
BLUEUTIL_PATH=/ops/homebrew/bin/blueutil
BT_DEVICE_ID="70-26-05-3b-ba-2c"

if [ $($BLUEUTIL_PATH --is-connected $BT_DEVICE_ID) == 1 ]; then
  $BLUEUTIL_PATH --disconnect $BT_DEVICE_ID || echo "Device not found..."
fi
