# Don't print a new line at the start of the prompt
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[battery]
disabled = false

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
[gcloud.project_aliases]
very-long-project-name = "vlpn"

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[nodejs]
disabled = true

[line_break]
disabled = false

[python]
disabled = true
