#!/bin/bash
set -e

if ! [ -d ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com jidonoso@gmail.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get 6xf6kufbb5bkxb2qcmjyesui74 .ssh/id_ed25519
onepassword_get swe5yyhv75b5bfd45h76rktisq .ssh/id_rsa

echo "Storing SSH keys in keychain..."
ssh-add -K
