#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

# Set zsh as the default shell
if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh jidonoso
fi

# Run macos script
$HOME/.macos

# Run scripts
script/extract-onepassword-secrets
script/install-vscode-extensions

# Add global docker compose services
docker-compose -p global -f $HOME/.docker-compose.global.yml up --no-start
