#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

# Set zsh as the default shell
if [ "$SHELL" != "/opt/homebrew/bin/fish" ]
then
  echo /opt/homebrew/bin/fish | sudo tee -a /etc/shells
  chsh -s /opt/homebrew/bin/fish jidonoso
fi

# Install fisher
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
fisher

# Run macos script
# $HOME/.macos

# Restore Mackup backups
mackup restore

# Setup fzf key bindings
$(brew --prefix)/opt/fzf/install

# Run scripts
# script/extract-onepassword-secrets
