#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

# Set zsh as the default shell
if [ "$SHELL" != "/usr/local/bin/fish" ]
then
  echo /usr/local/bin/fish | sudo tee -a /etc/shells
  chsh -s /usr/local/bin/fish jidonoso
fi

# Install fisher
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
fisher

# Run macos script
$HOME/.macos

# Run scripts
script/extract-onepassword-secrets
script/install-vscode-extensions
